### ISSUE TITLE
Tests are executed twice

### ISSUE THREAD

**Issue by pmwmedia** [fridujo/classpath-junit-extension#157]
I have just tried to write a test using your extension. However, tests are executed twice.

Minimal test class for reproducing the issue:

```java
import org.junit.jupiter.api.Test;
import com.github.fridujo.junit.extension.classpath.ModifiedClasspath;

public class FooTest {

	@Test
	@ModifiedClasspath
	void bar() {
		System.out.println("Test");
	}

}
```

Output in IntelliJ:
```
Test
Test
```

**Comment by ledoyen** [comment]
Hello 👋 

It's been a while since I look closely to this project.
As far as I remember, it's the whole point of using the extension, running the test with **and** without classpath modification.

In your case, there is no additional configuration, so the classpath is the same for the second run.

However if you look at the examples in the readme, this should be clearer.

It can also be a bug, as this project is a simple experimentation at this stage.

**Comment by pmwmedia** [comment]
I wasn't aware that the extension is about running the test with **and** without classpath modification.

Unfortunately, it's not exactly for what I'm looking for. However, your approach gives me good input for my own little extension :)

**Comment by ledoyen** [comment]
@pmwmedia after taking a closer look, it seems more like a bug (a side effect of the underlying JUnit invocation overriding).
Indeed, I was confused with another extension point of this lib, but, as the example you linked is a `@Test` and not a `@TestTemplate`, it should run only once.

**Comment by ledoyen** [comment]
I re-opened it so I can take a look when I make some time for it.

**Comment by ledoyen** [comment]
@pmwmedia I do confirm that the bug is due to an early design in the 1.0.0 version.

However it is fixed on the `master` branch but not yet released.

This is the second project I have to migrate from Travis (mostly re-setup the sonatype creds that are somewhere, maybe), and I do not have the time to do it in the short term.

Hopefully in a few months, I will have the opportunity to make these chores.

In the meantime, you can try it by building it yourself (git clone + mvn install) or with a branch ref using jitpack.

**Comment by pmwmedia** [comment]
Thank you!
